version: "3.9"

services:

  filemanager:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: filemanager
    env_file:
      - src/.env
    ports:
      - "8000:8000"
    volumes:
      - "./src:/var/www"
    networks:
      - filemanager

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9001:9001"
    volumes:
      - ./docker-data/data/minio/:/data
    env_file:
      - src/.env
    command: server --console-address ":9001" /data
    networks:
      - filemanager

networks:
  filemanager:
    driver: bridge
