"""create initial tables

Revision ID: 22f77b16a646
Revises: d88b1df2a3ec
Create Date: 2024-07-29 10:05:07.129997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f77b16a646'
down_revision: Union[str, None] = 'd88b1df2a3ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('uuid', sa.BINARY(length=16), nullable=False),
    sa.Column('credential', sa.JSON(), nullable=True),
    sa.Column('path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=32), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_files_uuid'), 'files', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_uuid'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
