"""tables

Revision ID: 6636fe22b643
Revises: 
Create Date: 2024-08-10 13:26:54.846187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6636fe22b643'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result', sa.BLOB(), nullable=True),
    sa.Column('date_done', sa.TIMESTAMP(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=155), nullable=True),
    sa.Column('args', sa.BLOB(), nullable=True),
    sa.Column('kwargs', sa.BLOB(), nullable=True),
    sa.Column('worker', sa.String(length=155), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('queue', sa.String(length=155), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_celery_tasks_task_id'), 'celery_tasks', ['task_id'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('credential', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('celery_task_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_celery_tasks_task_id'), table_name='celery_tasks')
    op.drop_table('celery_tasks')
    # ### end Alembic commands ###
