"""Initial tables

Revision ID: c151a87a9fdc
Revises: 
Create Date: 2024-08-03 07:18:14.001243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c151a87a9fdc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('credential', sa.JSON(), nullable=True),
    sa.Column('path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
